### ISSUE TITLE
bug: `Map already initialized` error while patching app

### ISSUE THREAD

**Issue by AlexVasiluta** [revanced/revanced-patcher#200]
### Type

Crash

### Bug description

Hello everyone!

I was using the revanced manager to patch Sync Pro with only the change oauth client id patch, but I got this relatively cryptic error.

I should note that, without the `reddit_client_id_revanced.txt` file, the patch is skipped, as it probably should be. However, when the file is present, the patch continues executing normally until it throws this error and aborts.

### Steps to reproduce

1. Create `reddit_client_id_revanced.txt` in the phone's root directory
2. Open revanced manager -> Sync Pro
3. Enable the change
4. Run patcher
5. Get error

### Relevant log output

```shell
Initializing installer
Creating working directory
Copying original apk
Unpacking input apk
Reading dex files
Decoding AndroidManifest.xml only, because resources are not needed
Merging integrations
An error occurred! Aborted
Error:
app.revanced.patcher.patch.PatchResultError: Map already initialized
	at app.revanced.patcher.fingerprint.method.impl.MethodFingerprint$Companion.initializeFingerprintResolutionLookupMaps$revanced_patcher(MethodFingerprint.kt:102)
	at app.revanced.patcher.Patcher$executePatches$1.invokeSuspend(Patcher.kt:348)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:129)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda-20(MainActivity.kt:326)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$Rd-IpIH_jmxD15EWmBEFM-jtGsk(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda13.run(Unknown Source:24)
	at java.lang.Thread.run(Thread.java:1012)
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by Mohamed-Aziz-Mhadhbi** [comment]
'This error suggests that there is an issue with initializing a map within the patching code. It's possible that the map is being initialized more than once, leading to a conflict and causing the error.'

Here are a few suggestions to troubleshoot the issue :

1. Verify that you are using the latest version of the revanced manager and Sync Pro. Updating both applications to their latest versions can help ensure compatibility and address any known issues.
2. Check if there are any known issues or bug reports related to the specific patch you are trying to apply. The revanced manager's documentation, GitHub repository, or community forums may provide insights into any known problems and potential workarounds.
3. Try removing the existing "reddit_client_id_revanced.txt" file and creating a new one. Ensure that the contents of the file are accurate and properly formatted.
4. If possible, try running the patching process on a different device or emulator to determine if the issue is specific to your current device.

I hope these suggestions help you in resolving the issue. If you have any further questions or need additional assistance, feel free to ask.

**Comment by AlexVasiluta** [comment]
It seems like the latest patch update from today (released after I posted the issue) for revanced fixed the bug. Thank you for your help!

**Comment by brian6932** [comment]
I'm still getting this

**Comment by Ushie** [comment]
ReVanced Manager does not use ReVanced Patcher V13 yet

**Comment by brian6932** [comment]
Ah, my bad should've prob checked revanced-manager instead, either way I used an older version of the manager and it worked, the patches I was using aren't compatible with the newest manager I think.
