### ISSUE TITLE
feat: provide api to access host apk version

### ISSUE THREAD

**Issue by zjns** [ReVanced/revanced-patcher#303]
### Feature description

Provide api to access host apk version name and version code.

### Motivation

Now we can access host apk package name through parsing AndroidManifest.xml, but we can't get version info in it, cause not existed. 
Sometimes I want to apply different patches directly based on the version of the host apk, for example, if it is lower than a certain version.

### Acknowledgements

- [x] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
I don't know how in scope it is for patcher to give you the ability to decide weather you want to add a patch or not. The purpose of patcher is only supposed for patching purposes. Patches can already read the version code and for example early return. Patches can also declare compatibility with certain version names. The reason version code is not used is because patches would need to provide both the version name and code because it would be unreadable to the user otherwise. And providing both doesn't make sense for patches, they only need one. Also you can parse the manifest of the host apk as well without patcher  via some library
